### ISSUE TITLE
请问你的MNN量化是怎么执行

### ISSUE THREAD

**Issue by haima1998** [wlguan/MNN-yolov3#2]
我尝试用MNN量化，会报以下错误，你有没有遇到这个问题
MNN/tools/quantization/calibration.cpp:189: Check failed: inputTensorStatistic != _featureInfo.end() ==> input tensor error!

我的配置文件这么来写 preprocessConfig.json，请问你是怎么写的，先谢了！
{
    "format":"RGB",
    "mean":[
        0.0,
        0.0,
        0.0
    ],
    "normal":[
        0.00392156,
        0.00392156,
        0.00392156
    ],
    "width":544,
    "height":544,
    "path":"/path/images",
    "used_image_num":500,
    "feature_quantize_method":"KL",
    "weight_quantize_method":"MAX_ABS"
}

**Comment by wlguan** [comment]
> 我尝试用MNN量化，会报以下错误，你有没有遇到这个问题
> MNN/tools/quantization/calibration.cpp:189: Check failed: inputTensorStatistic != _featureInfo.end() ==> input tensor error!
> 我的配置文件这么来写 preprocessConfig.json，请问你是怎么写的，先谢了！
> {
> "format":"RGB",
> "mean":[
> 0.0,
> 0.0,
> 0.0
> ],
> "normal":[
> 0.00392156,
> 0.00392156,
> 0.00392156
> ],
> "width":544,
> "height":544,
> "path":"/path/images",
> "used_image_num":500,
> "feature_quantize_method":"KL",
> "weight_quantize_method":"MAX_ABS"
> }

请问使用的是哪个MNN模型？

**Comment by wlguan** [comment]
> 我尝试用MNN量化，会报以下错误，你有没有遇到这个问题
> MNN/tools/quantization/calibration.cpp:189: Check failed: inputTensorStatistic != _featureInfo.end() ==> input tensor error!
> 我的配置文件这么来写 preprocessConfig.json，请问你是怎么写的，先谢了！
> {
> "format":"RGB",
> "mean":[
> 0.0,
> 0.0,
> 0.0
> ],
> "normal":[
> 0.00392156,
> 0.00392156,
> 0.00392156
> ],
> "width":544,
> "height":544,
> "path":"/path/images",
> "used_image_num":500,
> "feature_quantize_method":"KL",
> "weight_quantize_method":"MAX_ABS"
> }

544的好像有些问题,320的模型是可以正常量化的，稍等我之后看一下。

**Comment by apxlwl** [comment]
> 我尝试用MNN量化，会报以下错误，你有没有遇到这个问题
> MNN/tools/quantization/calibration.cpp:189: Check failed: inputTensorStatistic != _featureInfo.end() ==> input tensor error!
> 
> 我的配置文件这么来写 preprocessConfig.json，请问你是怎么写的，先谢了！
> {
> "format":"RGB",
> "mean":[
> 0.0,
> 0.0,
> 0.0
> ],
> "normal":[
> 0.00392156,
> 0.00392156,
> 0.00392156
> ],
> "width":544,
> "height":544,
> "path":"/path/images",
> "used_image_num":500,
> "feature_quantize_method":"KL",
> "weight_quantize_method":"MAX_ABS"
> }

这个咨询过MNN群中的大佬，括号中的几行可以先注释。即if (_featureQuantizeMethod == "KL") {}可以整个注释，不影响量化过程。

**Comment by haima1998** [comment]
> 大佬，括号中的几行可以先注释。即if (_featureQuantizeMethod == "KL") {}可以整个注释，不影响量化过程。

多谢了！ 注释掉if块后问题解决，MNN模型量化完成。
但是量化后的推理速度并未有明显提升，只是模型大小减小明显。

**Comment by apxlwl** [comment]
> > 大佬，括号中的几行可以先注释。即if (_featureQuantizeMethod == "KL") {}可以整个注释，不影响量化过程。
> 
> 多谢了！ 注释掉if块后问题解决，MNN模型量化完成。
> 但是量化后的推理速度并未有明显提升，只是模型大小减小明显。

我readme里有写，int8量化是针对arm设备的优化。
